# Generated by Django 3.2 on 2022-08-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_student_phone_number_p'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('name', 'phone_number'), name='unique student'),
        ),
    ]
