# Generated by Django 3.2 on 2022-08-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_student_unique student'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique student',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('name', 'phone_number'), name='unique_student'),
        ),
    ]
