# Generated by Django 3.2 on 2022-08-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('name', 'phone_number'), name='unique_teacher'),
        ),
    ]
